---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: claims-db
  namespace: dev
spec:
  encryptedData:
    ConnectionStrings__DefaultConnection: AgCqZhNt9UV2VPuO4oqpup+JGcbrTFmlq71uXQ10+oUXaN400Y1a/4wcEO0bH56zjeAeHy/20l66mrkdwtRDjg4W/D/CbQTt9EVb2dFguXhaLhyz8El7WB+HzIqR96oXJsCjNi3D0WbXGAeutGjRJTD2yUb7vW++MlBPBEZ7x8PEEN9TCxq192urVgsD8hBhstXmY/9e0+LZ64gK3c7knWHnfwj6tTkMKUMahxjPCpfwpxVJ0N8Sn3YHHULPkQuYeQnpL/KISrKb7b+QT5GbTmBTJxWSD6jiLQthDpH1nZ4B9m9+RuaEKGThIfx3ScazhFjMPmf/5Cp8JHRYwvRBtmOxhKaLN85wlZab/HY/xK0Y0s2N1PadqV3YwaPrwGOmTM3ESEhzsXNGNEL6vXpTPFMA4O/3lP327usFwWm2bY7XAI5gcYp6DWPR80L0kwdEO/jbQ13ZK/5Av7oUNHZhVTXc+NfgGB3bUxpYY6nO70MfRpc4dx83Bu9rx/JfWle0ZNiLfM7N7zgj2n7Tn7nIoEGGWgKc8vbtzrklG6AjcHHQ/5Mh6DY5ENeDR+/eLkNiN0sSINSui8lFhM06wk9RMjKq8vjk4WRDRKV8NEpdo39mYD6Q+eE4XJHbbLyj4MmIE2JrXXd+Sa0ceQHjUqOKU2t95Mtp3U34etSYv410o+6/Cb7Vf36ZVhCoCKxeCwQ7Nz+wKg+yxeKaAU47I7WNNQFkG6yqk6lL9NECGEbNGMBm8VT39wfpfroaMyGyufxlrPfBDM1KTh/S11oAIFiW2JwkJbWXdfaeahpVho5JmfpKw7EuUc2XDkEdw3D/H4Pq/WUcbCwFvo/bu/vngljq8TBOAO/ngKSdmOe/GxoD/RqLHqPnJevkx8TR+VfLwpvIsC71YUiG3SncqwE9v99uNswEWwDlOCZmesj/fp7PDatPHnJn0r6rT2EXwjd5MAFyoZ3Hyo15Evl+2ChyZ2FmVcl1pz12rmvXcLJcBZnCRPTCDml/fqyBoUgOIkavFHa13ocAhqVckWSj1hPtwPzooSKI7i/o00d707Q=
  template:
    metadata:
      name: claims-db
      namespace: dev
    type: Opaque
