apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-server"
  labels:
    app: {{ .Values.appName | quote }}
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    app: {{ .Values.appName | quote }}
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
