name: De-provision Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to destroy"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra/terraform/${{ github.event.inputs.environment }}

    environment:
      name: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
